# Generated by Django 5.0.3 on 2024-04-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_complexevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexevent',
            name='RSVP',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complexevent',
            name='event_time',
            field=models.CharField(max_length=50),
        ),
    ]
