# Generated by Django 5.0.3 on 2024-04-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_complexevent_rsvp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexevent',
            name='RSVP',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='complexevent',
            name='event_time',
            field=models.DateTimeField(),
        ),
    ]
