# Generated by Django 5.0.3 on 2024-04-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_complexevent_rsvp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexevent',
            name='RSVP',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='complexevent',
            name='event_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='complexevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
