# Generated by Django 5.0.3 on 2024-04-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_complexevent_rsvp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexevent',
            name='image',
            field=models.ImageField(default='C:/Cloud/Programming/Python/CodingProjects/Leaf/backend/placeholder.jpg', upload_to=''),
        ),
    ]
