# Generated by Django 5.0.3 on 2024-04-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_complexevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexevent',
            name='event_time',
            field=models.TextField(),
        ),
    ]
