# Generated by Django 5.0.3 on 2024-04-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_complexevent_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexevent',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='complexevent',
            name='image',
        ),
    ]
