# Generated by Django 5.0.3 on 2024-04-24 21:06
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_complexevent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complexevent',
            name='image',
        ),
        migrations.AddField(
            model_name='complexevent',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 0)),
        ),
    ]
