# Generated by Django 5.0.3 on 2024-04-24 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_complexevent_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexevent',
            name='event_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
