# Generated by Django 5.0.3 on 2024-04-24 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_complexevent_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexevent',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 0)),
        ),
    ]
