# Generated by Django 5.0.3 on 2024-04-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_complexevent_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='complexevent',
            name='image',
            field=models.ImageField(default='../assets/placeholder.jpg', upload_to='images/'),
        ),
    ]
